title: Centered Security
description: A Site discussing Security and Computer related topics!!
theme: just-the-docs
search_enabled: false 
favicon_ico: /fav.png
url: https://www.centeredsecurity.com
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  tests:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    blog:
      # Give the collection a name
      name: Blog
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
       nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

