title: Centered Security
description: A Site discussing Security and Computer related topics!!
theme: just-the-docs

url: https://www.centeredsecurity.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
